apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentication-service-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/authentication-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-service-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/business-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/frontend-service-role
